### PR TITLE
Standardized codebase

### PR DESCRIPTION
**Pull request by nikooo777**
With more and more people working on the APIs it's good to keep the source code nice and tidy.

With this PR I'm removing unused imports, fixing uneven tabulation, removing redundant keywords.

It's "juicy" but if you accept it and also enable auto formatting/imports cleanup on your end, it should be the only one.

I am running this branch on my gameserver and it works.

I suggest you compare changes by ignoring white spaces (it's a setting here on github when reviewing a PR) 
,
 though the best test is to just run it.

### CODE REVIEW

**Comment by Julgers** [comment]
Hey there, looks cool to me.
Does this MR make *any* functional changes to the code, or only tidying it up?

**Comment by moddedmcplayer** [comment]
Would it make sense to convert certain comments to #region preprocessor-directives?

**Comment by nikooo777** [comment]
As mentioned in discord, only tidies up the code and formats it.

@moddedmcplayer i think such change should be split from this PR as it's already big enough

**Comment by Julgers** [comment]
(not compatible with the latest changes anymore)

**Pull request closed without merging**
